#!/usr/bin/env python3
"""
Quantitative arm-tracking analysis for G1-23 + BrainCo teleoperation episodes.

Question answered: "If we tell the arm to move to a certain position, does it
really go there, at that exact position or not?"

Data source : xr_teleoperate EpisodeWriter JSON episodes (teleop/utils/data/<task>/episode_XXXX/data.json)
              - states.<side>_arm.qpos  = MEASURED joint position  [rad], read back over DDS
              - actions.<side>_arm.qpos = COMMANDED joint target   [rad], the IK solution sol_q
FK model    : xr_teleoperate/assets/g1/mode10/g1_23dof_mode_10_with_brainco.urdf
              reduced exactly as teleop/robot_control/robot_arm_ik.py:G1_23_ArmIK does
              (legs + waist_yaw + all BrainCo finger joints locked), with the L_ee/R_ee
              operational frames at <side>_wrist_roll_joint + [0.20, 0, 0] m.
              This is the same model the IK solved against, so FK here is consistent
              with what the operator was actually commanding.

Run:  conda activate tv-2 && python arm_tracking_analysis.py
"""
import os, sys, json, glob, csv, datetime
import numpy as np
import pinocchio as pin
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------------- config
DATA_ROOT   = "/home/cvl/xr_teleoperate/teleop/utils/data/pick cube"
URDF_PATH   = "/home/cvl/xr_teleoperate/assets/g1/mode10/g1_23dof_mode_10_with_brainco.urdf"
URDF_DIR    = "/home/cvl/xr_teleoperate/assets/g1/mode10"
OUT_DIR     = os.path.dirname(os.path.abspath(__file__))

# Cutoff separating sim episodes recorded against the CURRENT robot asset from those
# recorded against a superseded one. The fixed-base sim USD used by the teleop pick-cube
# task was regenerated on 2026-07-10 16:12 (per its config.yaml, "Generated by
# UrdfConverter on 2026-07-10 at 16:12:42"); sim episodes older than that ran against a
# robot model that no longer exists, so they do not describe the current system and are
# excluded from the plots and aggregates. They are still written to the per-session CSV,
# tagged asset="superseded", so nothing is silently dropped.
ASSET_CUTOFF_DATE = datetime.date(2026, 7, 10)

# Nominal record rate. There are no per-sample timestamps in the episode format.
# The sim episodes carry a whole-episode `sim_state._timestamp` at 1-SECOND resolution;
# its mean first-to-last slope over the long episodes is 29.8-29.9 Hz, which validates
# 30 Hz as the sample spacing. Physical episodes carry no clock at all.
FS_HZ = 30.0
DT    = 1.0 / FS_HZ

# Steady-state definition: commanded joint speed below this, sustained for SETTLE_S
# beforehand (so the sample is not merely at a velocity zero-crossing mid-swing).
STEADY_VEL_DEG_S = 2.0
SETTLE_S         = 0.5
SETTLE_N         = int(round(SETTLE_S * FS_HZ))

# Lag search window for cross-correlation, in samples (0 .. 2000 ms). Deliberately wide:
# the sim servo lag turned out to exceed 500 ms, so a narrow window would censor it.
# Any per-joint k that lands on the ceiling is flagged `lag_censored` in the output.
MAX_LAG_N = 60

JOINTS = ["shoulder_pitch", "shoulder_roll", "shoulder_yaw", "elbow", "wrist_roll"]
# DDS motor order of the dual-arm vector produced by G1_23_ArmController.get_current_dual_arm_q()
# (G1_23_JointArmIndex 15,16,17,18,19 then 22,23,24,25,26). Verified identical to the
# pinocchio reduced-model joint order, so the same 10-vector feeds both error stats and FK.
Q_NAMES = [f"left_{j}" for j in JOINTS] + [f"right_{j}" for j in JOINTS]


# ----------------------------------------------------------------------------- FK model
def build_fk():
    robot = pin.RobotWrapper.BuildFromURDF(URDF_PATH, URDF_DIR)
    lock = ["left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint",
            "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
            "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",
            "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
            "waist_yaw_joint"]
    for side in ("left", "right"):
        for f in ("thumb_metacarpal", "thumb_proximal", "thumb_distal",
                  "index_proximal", "index_distal", "middle_proximal", "middle_distal",
                  "ring_proximal", "ring_distal", "pinky_proximal", "pinky_distal"):
            lock.append(f"{side}_{f}_joint")
    ids = [robot.model.getJointId(n) for n in lock]
    red = robot.buildReducedRobot(list_of_joints_to_lock=ids,
                                  reference_configuration=np.zeros(robot.model.nq))
    for tag, jname in (("L_ee", "left_wrist_roll_joint"), ("R_ee", "right_wrist_roll_joint")):
        red.model.addFrame(pin.Frame(tag, red.model.getJointId(jname),
                                     pin.SE3(np.eye(3), np.array([0.20, 0.0, 0.0])),
                                     pin.FrameType.OP_FRAME))
    data = red.model.createData()
    order = [red.model.names[i] for i in range(1, red.model.njoints)]
    assert order == [f"{n}_joint" for n in Q_NAMES], f"joint order mismatch: {order}"
    return red.model, data, red.model.getFrameId("L_ee"), red.model.getFrameId("R_ee")


def fk_palm(model, data, fid, Q):
    """Q: (n,10) rad -> (positions (n,3) m, rotations (n,3,3)) of frame fid in pelvis frame."""
    P = np.empty((len(Q), 3)); R = np.empty((len(Q), 3, 3))
    for i, q in enumerate(Q):
        pin.forwardKinematics(model, data, q)
        pin.updateFramePlacement(model, data, fid)
        P[i] = data.oMf[fid].translation
        R[i] = data.oMf[fid].rotation
    return P, R


# ----------------------------------------------------------------------------- loading
def load_episode(ep_dir):
    """Return dict with the 10-DoF measured/commanded arrays and integrity flags.

    Two on-disk layouts exist:
      * legacy (episodes 0000-0021): the recorder sliced the 10-element dual-arm vector
        with q[:7] / q[-7:], so 'left_arm' holds q[0:7] and 'right_arm' holds q[3:10] --
        they OVERLAP by 4 elements and neither is a real arm. The true 10-vector is
        recovered losslessly as concat(left[0:7], right[4:7]); the overlap is verified
        elementwise on every frame before accepting the reconstruction.
      * current (episodes 0022+): correct 5/5 split.
    """
    with open(os.path.join(ep_dir, "data.json")) as f:
        blob = json.load(f)
    items = blob["data"]
    n = len(items)
    legacy = len(items[0]["states"]["left_arm"]["qpos"]) == 7

    S = np.empty((n, 10)); A = np.empty((n, 10)); bad = 0
    for i, it in enumerate(items):
        for M, key in ((S, "states"), (A, "actions")):
            l = np.asarray(it[key]["left_arm"]["qpos"], float)
            r = np.asarray(it[key]["right_arm"]["qpos"], float)
            if legacy:
                if not np.allclose(l[3:7], r[0:4]):
                    bad += 1
                M[i] = np.concatenate([l[0:7], r[4:7]])
            else:
                M[i] = np.concatenate([l, r])

    ts = None
    if isinstance(items[0].get("sim_state"), dict) and "_timestamp" in items[0]["sim_state"]:
        ts = np.array([it["sim_state"]["_timestamp"] for it in items], float)

    return dict(
        name=os.path.basename(ep_dir), path=ep_dir, n=n, legacy=legacy,
        q_meas=S, q_cmd=A, ts=ts,
        is_sim=isinstance(items[0].get("sim_state"), dict),
        date=datetime.date.fromisoformat(blob["info"]["date"]),
        overlap_violations=bad,
        # a repeated measured vector means the DDS state read back stale between record ticks
        stuck_meas=int(np.sum(np.all(np.diff(S, axis=0) == 0, axis=1))),
        stuck_cmd=int(np.sum(np.all(np.diff(A, axis=0) == 0, axis=1))),
    )


# ----------------------------------------------------------------------------- metrics
def err_stats(e_deg):
    """e_deg: 1-D signed error array in degrees."""
    a = np.abs(e_deg)
    return dict(mae_deg=float(a.mean()), rms_deg=float(np.sqrt((e_deg ** 2).mean())),
                p95_deg=float(np.percentile(a, 95)), max_deg=float(a.max()), n=int(a.size))


def best_lag(cmd, meas, max_lag=MAX_LAG_N):
    """k (samples, >=0) maximising corr(cmd[t-k], meas[t]). Returns (k, corr)."""
    c = cmd - cmd.mean(); m = meas - meas.mean()
    if c.std() < 1e-9 or m.std() < 1e-9:
        return 0, float("nan")
    best_k, best_r = 0, -np.inf
    # need a reasonable overlap left after shifting, else the correlation is meaningless
    max_lag = min(max_lag, max(0, len(cmd) - 30))
    for k in range(0, max_lag + 1):
        a = c[:len(c) - k] if k else c
        b = meas[k:] - meas[k:].mean()
        a = a - a.mean()
        if a.std() < 1e-9 or b.std() < 1e-9:
            continue
        r = float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))
        if r > best_r:
            best_r, best_k = r, k
    return best_k, best_r


def steady_mask(cmd_deg):
    """True where the commanded signal has been near-static for SETTLE_N samples."""
    v = np.abs(np.gradient(cmd_deg, DT))
    slow = v < STEADY_VEL_DEG_S
    m = slow.copy()
    for s in range(1, SETTLE_N + 1):
        m[s:] &= slow[:-s]
    m[:SETTLE_N] = False
    return m


def geodesic_deg(Ra, Rb):
    """Angle of the relative rotation Ra^T Rb, per sample, in degrees."""
    Rrel = np.einsum("nji,njk->nik", Ra, Rb)
    tr = np.clip((np.trace(Rrel, axis1=1, axis2=2) - 1.0) / 2.0, -1.0, 1.0)
    return np.degrees(np.arccos(tr))


# ----------------------------------------------------------------------------- main
def main():
    model, data, LID, RID = build_fk()
    eps = [load_episode(d) for d in sorted(glob.glob(os.path.join(DATA_ROOT, "episode_*")))]

    rows = []            # tidy per-session-per-joint rows
    palm_rows = []       # tidy per-session-per-arm task-space rows
    pooled = {}          # (env, era, side, joint) -> list of signed error arrays
    pooled_palm = {}     # (env, era, side) -> list of (pos_err_mm, ori_err_deg)
    sessions = []

    for ep in eps:
        env = "sim" if ep["is_sim"] else "physical"
        # Physical runs are unaffected by which sim asset was in use.
        asset = "current" if (not ep["is_sim"] or ep["date"] >= ASSET_CUTOFF_DATE) \
                else "superseded"
        era_eff = asset
        ep["asset"] = asset

        cmd_deg = np.degrees(ep["q_cmd"]); meas_deg = np.degrees(ep["q_meas"])
        dur_s = ep["n"] * DT

        sessions.append(dict(
            session=ep["name"], path=ep["path"], date=ep["date"].isoformat(), env=env,
            asset=asset, n_samples=ep["n"], duration_s=round(dur_s, 1),
            layout="legacy_7_7_overlap" if ep["legacy"] else "correct_5_5",
            overlap_violations=ep["overlap_violations"],
            stuck_measured_frames=ep["stuck_meas"], stuck_cmd_frames=ep["stuck_cmd"],
            has_per_sample_timestamps=False,
            has_episode_timestamp=ep["ts"] is not None,
        ))

        for j in range(10):
            side = "left" if j < 5 else "right"
            jname = JOINTS[j % 5]
            c, m = cmd_deg[:, j], meas_deg[:, j]

            e0 = m - c                                   # (i) zero-lag
            k, r = best_lag(c, m)                        # lag by cross-correlation
            ek = (m[k:] - c[:len(c) - k]) if k else e0   # (ii) lag-compensated
            sm = steady_mask(c)
            ess = e0[sm]

            s0, sk = err_stats(e0), err_stats(ek)
            row = dict(session=ep["name"], env=env, asset=asset, arm=side, joint=jname,
                       n_samples=ep["n"],
                       zerolag_mae_deg=s0["mae_deg"], zerolag_rms_deg=s0["rms_deg"],
                       zerolag_p95_deg=s0["p95_deg"], zerolag_max_deg=s0["max_deg"],
                       lag_k_ms=round(k * DT * 1000.0, 1), lag_xcorr_r=round(r, 4),
                       lag_censored=(k == min(MAX_LAG_N, max(0, ep["n"] - 30))),
                       lagcomp_mae_deg=sk["mae_deg"], lagcomp_rms_deg=sk["rms_deg"],
                       lagcomp_p95_deg=sk["p95_deg"], lagcomp_max_deg=sk["max_deg"],
                       steady_n_samples=int(sm.sum()))
            if sm.sum() >= 10:
                ss = err_stats(ess)
                row.update(steady_mae_deg=ss["mae_deg"], steady_rms_deg=ss["rms_deg"],
                           steady_p95_deg=ss["p95_deg"], steady_max_deg=ss["max_deg"],
                           steady_bias_deg=float(ess.mean()))
            else:
                row.update(steady_mae_deg=None, steady_rms_deg=None, steady_p95_deg=None,
                           steady_max_deg=None, steady_bias_deg=None)
            rows.append(row)
            if asset == "current":
                pooled.setdefault((env, side, jname), []).append(e0)
                pooled.setdefault((env, side, jname, "steady"), []).append(ess)

        # ---- task space
        for side, fid in (("left", LID), ("right", RID)):
            Pc, Rc = fk_palm(model, data, fid, ep["q_cmd"])
            Pm, Rm = fk_palm(model, data, fid, ep["q_meas"])
            dpos_mm = np.linalg.norm(Pm - Pc, axis=1) * 1000.0
            dori_deg = geodesic_deg(Rc, Rm)
            dz_mm = (Pc[:, 2] - Pm[:, 2]) * 1000.0     # vertical shortfall, +ve = robot low
            palm_rows.append(dict(
                session=ep["name"], env=env, asset=asset, arm=side, n_samples=ep["n"],
                pos_mae_mm=float(dpos_mm.mean()), pos_rms_mm=float(np.sqrt((dpos_mm**2).mean())),
                pos_p95_mm=float(np.percentile(dpos_mm, 95)), pos_max_mm=float(dpos_mm.max()),
                ori_mae_deg=float(dori_deg.mean()), ori_rms_deg=float(np.sqrt((dori_deg**2).mean())),
                ori_p95_deg=float(np.percentile(dori_deg, 95)), ori_max_deg=float(dori_deg.max()),
                z_shortfall_mean_mm=float(dz_mm.mean()), z_shortfall_max_mm=float(dz_mm.max()),
                cmd_z_range_mm=float((Pc[:, 2].max() - Pc[:, 2].min()) * 1000.0)))
            if asset == "current":
                pooled_palm.setdefault((env, side), []).append((dpos_mm, dori_deg, dz_mm))
            ep.setdefault("palm", {})[side] = (Pc, Pm, dpos_mm, dori_deg, dz_mm)

    # ---- aggregates
    agg = []
    for key, arrs in sorted(pooled.items(), key=lambda kv: str(kv[0])):
        steady = len(key) == 4
        env, side, jname = key[:3]
        e = np.concatenate(arrs) if arrs else np.array([])
        if e.size < 10:
            continue
        s = err_stats(e)
        agg.append(dict(env=env, arm=side, joint=jname,
                        window="steady_state" if steady else "all_samples",
                        n_samples=s["n"], mae_deg=s["mae_deg"], rms_deg=s["rms_deg"],
                        p95_deg=s["p95_deg"], max_deg=s["max_deg"],
                        bias_deg=float(e.mean())))
    agg_palm = []
    for (env, side), lst in sorted(pooled_palm.items()):
        dp = np.concatenate([a[0] for a in lst]); do = np.concatenate([a[1] for a in lst])
        dz = np.concatenate([a[2] for a in lst])
        agg_palm.append(dict(env=env, arm=side, n_samples=int(dp.size),
                             pos_mae_mm=float(dp.mean()), pos_rms_mm=float(np.sqrt((dp**2).mean())),
                             pos_p95_mm=float(np.percentile(dp, 95)), pos_max_mm=float(dp.max()),
                             ori_mae_deg=float(do.mean()), ori_rms_deg=float(np.sqrt((do**2).mean())),
                             ori_p95_deg=float(np.percentile(do, 95)), ori_max_deg=float(do.max()),
                             z_shortfall_mean_mm=float(dz.mean()), z_shortfall_max_mm=float(dz.max())))

    # ---- write outputs
    def dump_csv(path, dicts):
        if not dicts: return
        keys = list(dicts[0].keys())
        with open(path, "w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=keys); w.writeheader(); w.writerows(dicts)

    dump_csv(os.path.join(OUT_DIR, "metrics.csv"), rows)
    dump_csv(os.path.join(OUT_DIR, "metrics_palm.csv"), palm_rows)
    dump_csv(os.path.join(OUT_DIR, "metrics_aggregate_joint.csv"), agg)
    dump_csv(os.path.join(OUT_DIR, "metrics_aggregate_palm.csv"), agg_palm)
    dump_csv(os.path.join(OUT_DIR, "sessions.csv"), sessions)

    with open(os.path.join(OUT_DIR, "metrics.json"), "w") as f:
        json.dump(dict(
            generated=datetime.datetime.now().isoformat(timespec="seconds"),
            data_root=DATA_ROOT, fk_urdf=URDF_PATH,
            assumed_sample_rate_hz=FS_HZ, asset_cutoff_date=ASSET_CUTOFF_DATE.isoformat(),
            steady_state_def=dict(cmd_speed_below_deg_s=STEADY_VEL_DEG_S,
                                  sustained_for_s=SETTLE_S),
            lag_search_max_ms=MAX_LAG_N * DT * 1000.0,
            not_available_from_recorded_data=[
                "C: IK feasibility residual - the operator's requested wrist pose "
                "(tele_data.left/right_wrist_pose) is consumed by solve_ik and never persisted "
                "to any log stream. Only the IK OUTPUT (sol_q) is recorded.",
                "E: end-to-end latency - no per-sample timestamps exist; the only clock in the "
                "format is sim_state._timestamp at 1-second resolution, sim episodes only, "
                "from a single process.",
            ],
            sessions=sessions, per_session_joint=rows, per_session_palm=palm_rows,
            aggregate_joint=agg, aggregate_palm=agg_palm), f, indent=2)

    make_plots(eps, agg, pooled_palm)
    print(f"wrote outputs to {OUT_DIR}")
    return eps, rows, palm_rows, agg, agg_palm, sessions


# ----------------------------------------------------------------------------- plots
def _style():
    plt.rcParams.update({"font.size": 17, "axes.titlesize": 21, "axes.labelsize": 18,
                         "xtick.labelsize": 15, "ytick.labelsize": 15, "legend.fontsize": 15,
                         "figure.dpi": 220, "savefig.dpi": 220, "axes.grid": True,
                         "grid.alpha": 0.3, "lines.linewidth": 2.4})


def make_plots(eps, agg, pooled_palm):
    _style()
    GROUPS = ["sim", "physical"]
    LABEL  = {"sim": "simulation", "physical": "physical robot"}
    COL    = {"sim": "#0353a4", "physical": "#2a9d8f"}
    # Only sessions recorded against the current robot asset describe the current system.
    cur = [e for e in eps if e["asset"] == "current"]

    def pick(env):
        c = [e for e in cur if (e["is_sim"] == (env == "sim"))]
        # representative reaching motion = largest commanded vertical excursion
        return max(c, key=lambda e: e["palm"]["left"][0][:, 2].ptp()) if c else None

    # -- Plot 1: commanded vs achieved palm height
    def draw(ax, e, env, lo=None, hi=None, tag=""):
        Pc, Pm = e["palm"]["left"][0], e["palm"]["left"][1]
        sl = slice(lo, hi)
        t = (np.arange(len(Pc)) * DT)[sl]
        ax.plot(t, Pc[sl, 2] * 1000, color="k", ls="--", label="commanded (IK target)")
        ax.plot(t, Pm[sl, 2] * 1000, color=COL[env], label="achieved (measured)")
        ax.fill_between(t, Pm[sl, 2]*1000, Pc[sl, 2]*1000, color=COL[env], alpha=.20,
                        label="vertical shortfall")
        sag = (Pc[sl, 2] - Pm[sl, 2]) * 1000
        n = len(t)
        ax.set_title(f"{LABEL[env]}{tag} — {e['name']}  (n={n:,}, {n*DT:.0f} s)\n"
                     f"commanded z range {Pc[sl,2].ptp()*1000:.0f} mm | "
                     f"mean shortfall {sag.mean():+.1f} mm, max {sag.max():+.1f} mm",
                     fontsize=16)
        ax.set_xlabel("time [s]"); ax.legend(loc="best", framealpha=.92, fontsize=13)

    e_sim, e_phy = pick("sim"), pick("physical")
    fig, axes = plt.subplots(1, 3, figsize=(25, 7.8))
    if e_sim is not None:
        draw(axes[0], e_sim, "sim")
    if e_phy is not None:
        draw(axes[1], e_phy, "physical")
        # zoom on the 20 s window containing the largest commanded vertical excursion
        z = e_phy["palm"]["left"][0][:, 2]
        W = int(20 * FS_HZ)
        ptp = np.array([z[i:i+W].ptp() for i in range(0, len(z) - W, 15)])
        i0 = int(np.argmax(ptp)) * 15
        draw(axes[2], e_phy, "physical", i0, i0 + W, tag=", zoom on largest reach")
    axes[0].set_ylabel("left palm height z [mm]  (pelvis frame)")
    fig.suptitle("Commanded vs achieved palm height — G1-23 + BrainCo", fontsize=23)
    fig.tight_layout(); fig.savefig(os.path.join(OUT_DIR, "plot1_palm_height.png")); plt.close(fig)

    # -- Plot 2: per-joint tracking error, sim vs physical
    fig, axes = plt.subplots(1, 2, figsize=(19, 8), sharey=True)
    x = np.arange(len(JOINTS)); w = 0.36
    for ax, side in zip(axes, ("left", "right")):
        for i, env in enumerate(GROUPS):
            mae, p95, ns = [], [], []
            for j in JOINTS:
                r = [a for a in agg if (a["env"], a["arm"], a["joint"], a["window"])
                     == (env, side, j, "all_samples")]
                mae.append(r[0]["mae_deg"] if r else np.nan)
                p95.append(r[0]["p95_deg"] if r else np.nan)
                ns.append(r[0]["n_samples"] if r else 0)
            err = np.array(p95) - np.array(mae)
            ax.bar(x + (i - 0.5) * w, mae, w, yerr=[np.zeros_like(err), err], capsize=6,
                   color=COL[env], label=f"{LABEL[env]} (n={max(ns):,}/joint)",
                   error_kw=dict(lw=1.8))
        ax.set_xticks(x); ax.set_xticklabels([j.replace("_", "\n") for j in JOINTS])
        ax.set_title(f"{side} arm"); ax.set_xlabel("joint")
    axes[0].set_ylabel("joint tracking error [deg]\nbar = MAE, whisker to p95")
    axes[0].legend()
    fig.suptitle("Per-joint arm tracking error (commanded vs measured, zero-lag)", fontsize=23)
    fig.tight_layout(); fig.savefig(os.path.join(OUT_DIR, "plot2_per_joint_error.png")); plt.close(fig)

    # -- Plot 3: CDF of palm position error
    fig, ax = plt.subplots(figsize=(13, 8.5))
    for env in GROUPS:
        for side, ls in (("left", "-"), ("right", "--")):
            lst = pooled_palm.get((env, side))
            if not lst: continue
            d = np.sort(np.concatenate([a[0] for a in lst]))
            ax.plot(d, np.arange(1, d.size + 1) / d.size * 100, ls=ls, color=COL[env],
                    label=f"{LABEL[env]} — {side} (n={d.size:,})")
    ax.set_xscale("log"); ax.set_xlabel("palm position error [mm]  (log scale)")
    ax.set_ylabel("percentage of samples at or below [%]")
    ax.set_title("CDF of task-space palm position error")
    ax.axhline(95, color="grey", lw=1.2, ls=":"); ax.text(1.05, 96, "p95", color="grey")
    ax.axhline(50, color="grey", lw=1.2, ls=":"); ax.text(1.05, 51, "median", color="grey")
    ax.legend(fontsize=14, loc="lower right")
    fig.tight_layout(); fig.savefig(os.path.join(OUT_DIR, "plot3_palm_error_cdf.png")); plt.close(fig)


if __name__ == "__main__":
    main()
